// 路由名称常量
export const ROUTE_NAMES = {
  home: 'Home',
  discover: 'Discover',
  recommendations: 'Recommendations',
  nearby: 'Nearby',
  randomPick: 'RandomPick',
  budgetTravel: 'BudgetTravel',
  travelerReviews: 'TravelerReviews',
  trendingViews: 'TrendingViews',
  spotList: 'SpotList',
  spotDetail: 'SpotDetail',
  guideList: 'GuideList',
  guideDetail: 'GuideDetail',
  orderCreate: 'OrderCreate',
  search: 'Search',
  profile: 'Profile',
  activity: 'Activity',
  settings: 'Settings',
  orderList: 'OrderList',
  orderDetail: 'OrderDetail',
  favorites: 'Favorites',
  reviewList: 'ReviewList',
  login: 'Login',
  register: 'Register'
}
